### ISSUE TITLE
Losing connectivity to host after some time

### ISSUE THREAD

**Issue by tdsotm** [Salvoxia/docker-openvpn-tap#17]
I'm sorry for creating an issue, but there's no discussions option so I can ask my question.
I've been  using this container for about a year, and I often experience that the clients are not able to connect. ssh to the machine fails to work, I can only login via the console option from my proxmox node, and the only fix I have is to reboot the vm. The VM is running on ubuntu 24.04. and I don't have NetworkManager. The service unit cannot be found and nmcli is not found on the system. I don't know how to debug the issue, nor the image I used since the image used was latest.
I think it's time to upgrade, in order to see if the problem is fixed, but I'm not sure if stopping the container and starting a new one using the same config would work without issues. For the reference this is my compose.yml:
```
version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: salvoxia/openvpn-tap
    container_name: openvpn
    network_mode: host
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    environment:
          - NFT_TABLES={$NFT_TABLES:-1}
```
